# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

# version: '3.4'

# services:
#   restapi:
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 8080:80

version: '3.4'
services:
  myskyl:
    build: database 
    container_name: myskyl
    environment: 
      MYSQL_ROOT_PASSWORD: "password"
    ports: 
      - "3306:3306"
  restapi:
    build: restapi
    ports: 
      - "8080:80"